### ISSUE TITLE
Kerberos support 

### ISSUE THREAD

**Issue by geoHeil** [locationtech/geowave#1042]
What is the state of kerberos support for geowave?

**Comment by rfecher** [comment]
Its on the road map. The idea would be for the GeoWave commandline tools to borrow roughly what Accumulo shell is doing to generate the AuthenticationToken such that you can use a KerberosToken.  Other extension points such as GeoServer datastore and raster coverage configuration are auto-populated from the commandline parameters so the goal would be to directly map the accumulo shell commandline parameters to parameter within each of geowave's extension points.

**Comment by rfecher** [comment]
This is related to #811

**Comment by nmehta92** [comment]
In order to implement the Kerberos authentication protocol in Geowave, we would need a centralized key-distribution center(KDC). This service will coordinate authentication between a client and a server. KDC administrator will provide name and the password to each client and server which will be used in authentication process. Clients and servers can use the tickets securely sent to them in the password by KDC, to communicate with KDC and prove their identity. 
 
To interact with Kerberos programmatically, we would have to implement two standards i.e. GSSAPI and SASL which allow cross-language integration with Kerberos for authentication. The Java programming language itself implements GSSAPI which can be leveraged by Geowave. The Java GSS-API contains the Java bindings which offers application programmers uniform access to security services of Kerberos atop a variety of underlying security mechanisms. SASL provides mechanism for authentication.

**Comment by nmehta92** [comment]
To investigate further about how can we implement this in Geowave, I went through the process flow of Kerberos authentication. There are two main steps to authentication with Kerberos. 
1. Initially, the client sends Authentication Service(AS) Request to KDC. User Key is used to encrypt and decrypt this AS request. KDC sends Authentication Service Reply which is encrypted using KDC's secret long term key. 
2. Once all the key components are setup, client requests for the specific service using Ticket Granting Ticket (TGT) provided to it by KDC in AS reply. The KDC replies with encrypted service ticket and session key. Using this information, the client sends Kerberos Application Request to access the desired service. After authenticating the client, the service sends back Kerberos Application Reply with encrypted timestamp. When client decrypts the reply and compares the timestamp, he knows that the service is genuine.

I think following would be the key points to consider when implementing Kerberos
1. Creation of KDC and its administrator
2. Creation of Kerberos names/principals for all server processes (Hadoop datanodes and namenode(s), ZooKeepers), 
3. Creation of a keytab file for each principal
4. Creation of other keys like session key, KDC long term secret, TGT session key, etc.
5. Forming and securely sending tokens (requests and reply) from client to server and to KDC

**Comment by nmehta92** [comment]
One more thing would be how to parallelize tasks across many nodes. This would require securely sharing the user credentials  across these tasks in as safe a manner as possible. One way would be to create on-the-fly password after authenticating with the user's credentials. Since the clients use MapReduce to interact with Accumulo, these on-the-fly tokens could be  delegated in parallel and securely.

Though it would be expensive to generate passwords on-the-fly for each message that is being exchanged along with the complex Kerberos protocol, it would be more secure than distributing the user’s credentials across the cluster. If these generated passwords are hacked, only access to HDFS, YARN and Accumulo would be compromised. If the token with credentials is hacked, the entire KDC would be compromised.

Further, I would look in detail implementation of Kerberos on client and server side and how to ensure the security of KDC and integrity of tokens.

**Comment by nmehta92** [comment]
After going through the two java files given in the #811, following are my findings -
1. the commandline for geowave can refer to the code as many parameters are same.
2. It is possible to integrate Kerberos authentication in Geowave, similar to Accumulo shell 
3. There is a flag called "useSasl" in clientconfig which determines should Kerberos authnetication be enabled or not
4. If this is true, then the password can be made optional and Kerberos Token can be used from the package  "org.apache.accumulo.core.client.security.tokens.KerberosToken". This will be used as authentication token rather than password. This is a secure way as compared to password. I had discussed one way of generating token on-the-fly to provide strong security but at the expense of higher rate.

**Comment by rfecher** [comment]
Support using keytab files is covered in PR #1738
