### ISSUE TITLE
configure coordinate

### ISSUE THREAD

**Issue by WangSmallHui** [locationtech/geowave#1356]
when I execute command "geowave config addindex" ,how can I configure my coordinate system? the EPSG:4326 used ,and can i change it ?

**Comment by rfecher** [comment]
`-c` or `--crs` 
...
because it is particular to spatial and spatial_temporal index types you have to activate one of those types before the help will print it, so
`geowave config addindex -t spatial --help` would show you the full set of spatial options.

Also, there was a bug associated with CRS's that have infinite bounds in 0.9.7 that is fixed in our latest and will be working good in the 0.9.8 release.  All other CRS's should work in 0.9.7.

**Comment by WangSmallHui** [comment]
thank you.... i will try it,and I will ask you if i have a question
