### ISSUE TITLE
Incorrect Feature count on WFS Queries from HBase

### ISSUE THREAD

**Issue by worky68** [locationtech/geowave#1365]
We have created an HBase Datastore in Geoserver using the GeoWave plugin. We then make requests using the WFS service in Geoserver to this Datastore. Inside of this Datastore we have ingested a number of SimpleFeatures with row visibility set. In addition, we have our own implementation of AuthorizationSPI that we use to filter results.

## Expected Behavior
We expect the WFS numOfFeatures attribute to reflect the number of features returned with the current response.

## Actual Behavior
The WFS numOfFeatures attribute reflects the total number of features within the Datastore regardless of the authorizations provided. However, the features returned in the resulting featurecollection are correct in terms of the authorizations provided.

## Workaround
The problem seems to stem from two places within the code that prefer a cached count over the actual count. As a workaround to the issue, we have removed the code below.

https://github.com/locationtech/geowave/blob/e9d9966fd908155205613d1a046c02cae1e40b20/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveFeatureCollection.java#L71-L87

https://github.com/locationtech/geowave/blob/e9d9966fd908155205613d1a046c02cae1e40b20/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveFeatureSource.java#L120-L126

After removing the code we are now receiving the proper count on our queries. Of course, sacrificing some efficiency. 

## Specifications

  - Version: 0.9.4

**Comment by rfecher** [comment]
Thanks @worky68 for this good supporting documentation along with the issue.  Apologies for not following up immediately, the developers were pushing hard to get 0.9.8 released and now we're going to investigate this prior to 1.0.0.

**Comment by rfecher** [comment]
after investigating, I believe this is a bug in 0.9.4 related to how we cache statistics results in HBase that no longer exists.
In 0.9.4 we'd cache the count result the first time regardless of authorizations [here](https://github.com/locationtech/geowave/blob/v0.9.4/extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/metadata/HBaseDataStatisticsStore.java#L234).

We currently [cache statistics](https://github.com/locationtech/geowave/blob/v0.9.8/core/store/src/main/java/mil/nga/giat/geowave/core/store/metadata/DataStatisticsStoreImpl.java#L129) results only associated by appropriate authorizations. 

We also have fairly involved testing with visibility/auth but I noticed for our primary integration test we use a Count Aggregation rather than a statistic.  I added to that test t o also verify statistics are using proper authorization in PR #1429 ... thanks for the feedback, in that it helped bulk up our testing.  Please re-open if by chance I am mistaken and you find this still to be an issue in 0.9.8, but I am _fairly_ confident this was resolved.

**Comment by worky68** [comment]
Thanks @rfecher! We are planning to upgrade to 1.0.0 in the future.
