### ISSUE TITLE
How to congiure --numPartitions and --partitionStrategy

### ISSUE THREAD

**Issue by scially** [locationtech/geowave#1411]
I want to know how to properly set numPartitions and partitionStrategy, I am using HBase, my data format is shapefile, a total of 7434km2
```
geowave config addindex -t spatial  -np 1024 -ps HASH fwm3-spatial
geowave config addstore  -t hbase -z server7:2181,server8:2181,server9:2181 --gwNamespace geowave.hwang fwm3
geowave ingest localtogw ./fwm.shp fwm3 fwm3-spatial
geowave gs addlayer -ws gepwave fwm3
```
I ause mapbox-vector slices, and Distributed environment also. But I found that the slicing speed is very slow, I guess this is related to numPartitions and partitionStrategy, so I would like to know how to set these parameters. As shown below.
![1](https://user-images.githubusercontent.com/22127608/45487604-6ce6b500-b791-11e8-8b13-9192f0ad6b1f.png)
I also configured Accumulo( pseudo-cluster), and GeoMesa , then imported the same data, I feel better.As shown below.
![2](https://user-images.githubusercontent.com/22127608/45487605-6eb07880-b791-11e8-83a4-b6b8ca217c5b.png)

Is this related to Accumulo and Hbase?

Geoserver:
![3](https://user-images.githubusercontent.com/22127608/45487748-d8c91d80-b791-11e8-8542-93cd287679cc.png)

**Comment by scially** [comment]
When i exec `geowave ingest`, there are some errors, but Geowave can still execute successfully.
```

13 Sep 19:40:38 ERROR [operations.HBaseOperations] - Error accessing region info: org.apache.hadoop.hbase.NotServingRegionExcep                                      tion: Region geowave.hwang_SPATIAL_IDX_HASH_1024,,1536838837869.053bd602805332010b3fc76b105dedea. is not online on server3,60020,15                                      36381559992
        at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:2997)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1069)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.splitRegion(RSRpcServices.java:1870)
        at org.apache.hadoop.hbase.protobuf.generated.AdminProtos$AdminService$2.callBlockingMethod(AdminProtos.java:22247)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2191)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
```

**Comment by rfecher** [comment]
it looks like you're configuring partitions with `-np` and `-ps`. I always do the verbose style using something like `--partitionStrategy round_robin --numPartitions 32` ... I think 1024 partitions is likely _dramatically_ too much for the amount of data you have?  It'd help to know the size of the cluster and the total number of geometries to get a feel, but I'd consider 1024 very highly distributed only for massive datasets on fairly large scale compute environments. I also am guessing you're working off the latest on the master branch judging by that error.  There was a recent PR merged that should resolve that for you (and we're looking at a 0.9.8 release very soon).

As for Accumulo v HBase, feel free to try us on both.  I wouldn't say either is better or worse in general, but under specific circumstances there are naturally going to be different characteristics exhibited on each.  With that said, if you have a strong preference for HBase, you really shouldn't see considerable differences, so my recommendation is to stick with it.

It may also be worth giving our "Distributed Rendering" a shot (I'm not sure of the data volume so I can't say for sure).  But what it does for you is push the vector tile production to the data nodes so that they can send GeoServer a vector tile representing all the data on the region server and GeoServer just needs to composite the vector tiles from the data nodes rather than a single machine needing to render potentially millions of geometries (but again, I don't know data volume so I can't say for sure this is a bottleneck for you).  [Here's](https://github.com/locationtech/geowave/blob/master/examples/data/slds/DistributedRender.sld) an example SLD, there's just a section you have to add to trigger GeoWave to use distributed rendering.  Another rendering trick that _really_ helps out with massive point data on a spatial index is [SubsamplePoints](https://github.com/locationtech/geowave/blob/master/examples/data/slds/SubsamplePoints.sld) but for this line/poly data that technique would produce some inconsistency.

**Comment by scially** [comment]
I am so excited that I have been looking forward to the release of version 0.9.8. I have also asked you about the coordinate system some time ago, and have been waiting for the official release of 0.9.8.
Thank you for your patience, I will study and operate immediately, and then discuss with you.

**Comment by rfecher** [comment]
Great!  Thanks for your patience!  The other concern I have is the way I suggested changing the charset may be heavy handed.  Charset encoding and decoding _can_ be very expensive for some charsets considering how often it needs to happen and the change I have you globally changes the charset for everything in GeoWave from one that we find pretty efficient to one that I don't know much about.  I am wondering if there is a smarter way to do that where it is only applied to certain attributes rather than globally...

**Comment by scially** [comment]
```
push the vector tile production to the data nodes so that they can send GeoServer a vector tile representing all the data on the region server and GeoServer just needs to composite the vector tiles from the data nodes
```
When I use GeoWave, does GeoWave cut the data by z-indexes and store it in Hbase. When I use GeoServe to load it, I feel that it should be sliced by GeoServer-MapBoxVector. But according to what you mean, can GeoWave also slice?

**Comment by scially** [comment]
So i would ask that can Gwoeave replace mapbox plugin？thanks...

**Comment by rfecher** [comment]
so, regarding distributed rendering, we basically just reuse GeoTools `StreamingRenderer` that does all the WMS rendering for ever other format.  Basically within GeoServer it incrementally builds the response, and even handles multithreaded production (so it can merge results from multiple thread), we just take that a step further and run it distributed.

However, I took a peak at the VectorTileOutputFormat and it looks to be one of the exceptions that does *not* use `StreamingRenderer`.  It looks like any WMS format that derives from `RenderedImageMapOutputFormat` will work.  So I actually wouldn't expect this to work for vector tiles out of the box.

Sorry for being misleading on that!  It conceptually seems the same thing _can_ be done for vector tiles - it uses a `PipelineBuilder` to do most of the heavy lifting that shares some resemblance to `StreamingRenderer` but `PipelineBuilder` is actually _way, way_ simpler because it doesn't have to handle all the generalized use cases that `StreamingRenderer` does.

**Comment by scially** [comment]
I ingest the samp shapefile by geowave, and set `--partitionStrategy round_robin --numPartitions 64`,but The effect is not very good. I feel that the loading speed is still very slow
![2-round-64](https://user-images.githubusercontent.com/22127608/45524535-8293c300-b801-11e8-8034-5fc97f7f6f07.png)
And there will be a slice failure
![1](https://user-images.githubusercontent.com/22127608/45524575-aeaf4400-b801-11e8-8e2a-61af4ce33c3e.png)
There are  my cluster configuration
![3](https://user-images.githubusercontent.com/22127608/45524612-e0280f80-b801-11e8-8cc1-1bd1674e1529.png)
![5](https://user-images.githubusercontent.com/22127608/45524613-e1593c80-b801-11e8-977f-70c056631016.png)

**Comment by scially** [comment]
Aboutthe Charset problem, I think it is possible to specify the encoding only when reading the Shapefile and then use other encodings on HBase.

**Comment by rfecher** [comment]
re: Charsets, isn't that what you tried in issue #1386?  Perhaps leave the charset setting as the geowave default everywhere to see what the impact on performance is?

**Comment by scially** [comment]
‘’‘ It'd help to know the size of the cluster and the total number of geometries  ‘’‘
![45524613-e1593c80-b801-11e8-977f-70c056631016](https://user-images.githubusercontent.com/22127608/45526627-7e1fd800-b80a-11e8-945f-55e27e1859a2.png)
And the size of  shapefile  is 350M, it is all data of Guangzhou, China
![_20180914104327](https://user-images.githubusercontent.com/22127608/45526749-0900d280-b80b-11e8-9fbd-0b63a150e895.png)

I want to know if there are other optimizations or configures when importing big shapefile?

**Comment by scially** [comment]
Sorry to bother you @rfecher , Does `HASH` refer to the `GeoHash` algorithm? I did not find the information of `ROUND_BOUIN`. How does it work? OpenLayer fails in GeoServer when I use `ROUND_BOUIN`...

**Comment by rfecher** [comment]
there is an open distributed rendering issue which I think is where this issue left off
