### ISSUE TITLE
Sandbox S3 image access denied

### ISSUE THREAD

**Issue by sunapi386** [locationtech/geowave#1520]
On the [Quickstart Tutorial](https://locationtech.github.io/geowave/sandbox-env.html#) page, the link to [VirtualBox_HDP_Geowave_Sandbox_1.0.0-SNAPSHOT.ova](https://s3.amazonaws.com/geowave-vm/1.0.0-SNAPSHOT/VirtualBox_HDP_Geowave_Sandbox_1.0.0-SNAPSHOT.ova) is broken. 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C6139114EB0E0D9B</RequestId>
<HostId>
hMV92sfNJZGoqo1rUFKBHaAjwD/lYvUlheGjcliFczcqV7xDIa8EzxsxLCz1UjNk7Gd5z0VlLSo=
</HostId>
</Error>
```

**Comment by rfecher** [comment]
it actually doesn't exist - we haven't been building dev sandbox VMs off of SNAPSHOT.  It used to link to the most recent release, but instead you can simply follow along with the most recent release here: http://s3.amazonaws.com/geowave/0.9.8/docs/quickstart.html

the links to the VM are versioned accordingly, so 0.9.8 is [here](https://s3.amazonaws.com/geowave-vm/0.9.8/VirtualBox_HDP_Geowave_Sandbox_0.9.8.ova)

the sandbox VM is going to be deprecated soon, particularly because its based off of Hortonworks Data Platform which is going away (Hortonworks was acquired by Cloudera and the last I heard they will merge their offerings into Cloudera Data Platform).  Instead we plan to keep the EMR quickstart guide as is, and streamline the local quickstart guide to just run on any OS, but without the entire Hadoop ecosystem.  With the support for Redis and RocksDB that is in 1.0.0-SNAPSHOT it is actually very easy and lightweight to run things locally on any OS.

**Comment by sunapi386** [comment]
Thanks for your reply! 

I thought I'd get the 1.0.0 since it's the latest and greatest. But 0.9.8 could do for playing around. 

Once the VM is deprecated, would that be replaced with docker images? I found prebuilt docker images such as [geodocker](https://github.com/geodocker/geodocker) and [geodocker-accumulo-geowave](https://github.com/geodocker/geodocker-accumulo-geowave) but they both seems a little outdated.

My main use case is actually do play around in the sandbox, ingress with a small amount of data with [PDAL reader/writer](https://pdal.io/stages/readers.geowave.html). PDAL supports [Entwine](https://pdal.io/stages/readers.ept.html) as well, so I wanted to do performance benchmarks. I have several TBs of point cloud data, so I'm not sure if Entwine data store is high performance enough. I don't have a well defined metric of what it means to be "high performance" but I suspect being able to handle geospatial bounding box queries quickly. Entwine supports [Potree](http://www.potree.org/) which makes like it a bit more, simply because I haven't figured out how to get Geowave/Geomesa to work with Potree.

**Comment by rfecher** [comment]
That makes sense.  Unfortunately we also stopped producing the C++ binaries at 0.9.7 if you look at "c++" under release RPMs [here](http://locationtech.github.io/geowave/packages.html), which is required for the PDAL writer.  Its not hard to produce but could be a challenge without deeper geowave experience.

Also, I wouldn't say the VM has ever been a good opportunity to "benchmark" _anything_.  On the plus side, its an opportunity to "play with" _everything_ but it is the entire Hortonworks/Hadoop ecosystem on a single host. For that "play with" concept we're switching to simply using RocksDB or Redis which we could include in docker, but is also very simple to run with directly on any host OS (RocksDB is just embedded, no separate install, and geowave merely requires a JVM).

If you have access to AWS and EMR, the most straightforward approach for real-world, distributed experience (eg. for benchmarking) rather than the "easy play" experience would be to just use our [EMR bootstrap scripts](http://locationtech.github.io/geowave/aws-env.html#bootstrap-scripts) to layer geowave on top of EMR.

**Comment by sunapi386** [comment]
Thanks for your detailed reply! 

I setup EMR with Geowave last week and followed the vector examples, just to see things worked out. But I prefer to develop offline to avoid the cost of keeping an EMR cluster running when I don't need (they don't have shutdown/pause, only terminate... and that means I have to bootstrap again re-copy over data, which takes like half hour to setup).

Regarding C++ binaries, I probably won't be affected as long as the PDAL Geowave writer continues to work with future Geowave versions > 0.9.7.

I am writing an adapter of my point cloud data format to PDAL reader/writer, so that I can store it in Geowave (possibly geomesa) or Entwine Point Format in the future with just a `pdal` command.

**Comment by rfecher** [comment]
A few things to just be aware of to keep cost down is 
- you can request spot instances for EMR which is often a fraction of the cost
- you can run HBase on S3 rather than HDFS which means you can terminate the cluster and bring another pointing at the same S3 URL and all of the data will be there, although for this option keep in mind S3 I/O performance is surprisingly pretty decent, but sometimes dramatically fluctuating and never as good as HDFS performance where the ephemeral storage is local (particularly if you use instance types with SSDs)
- HBase and Accumulo both have table export and import options so you can likely script it to store data on S3 regardless before terminating a cluster and always re-import tables from S3, but you'd have to put in some time to get that working right.

**Comment by rfecher** [comment]
The quickstart guide us updated to discontinue sandbox usage and instead use the new standalone installer
