### ISSUE TITLE
does Geowave support group by query?

### ISSUE THREAD

**Issue by scially** [locationtech/geowave#1606]
`org.locationtech.geowave.core.store.api.AggregationQuery` support `group by` query?

**Comment by rfecher** [comment]
GeoWave's aggregations provide the ability to simply return a statistic from the query rather than each result.  For example, a count is the most basic, but also vector data provides these out of the box: https://github.com/locationtech/geowave/blob/master/core/geotime/src/main/java/org/locationtech/geowave/core/geotime/store/query/api/VectorAggregationQueryBuilder.java#L43-L85

If you really want to customize, you can write your own aggregation to do anything you want on your data. If you're running Accumulo or HBase with server-side libraries enabled (default settings) then you have to make sure any new aggregations you write are also in the server-side library.  Here's the Aggregation interface, which if you wanted to group results within the context of the aggregation, it can be implemented here: https://github.com/locationtech/geowave/blob/master/core/store/src/main/java/org/locationtech/geowave/core/store/api/Aggregation.java#L95
