### ISSUE TITLE
CLI - list of utility commands differ between standalone install and source code built

### ISSUE THREAD

**Issue by pfrollo** [locationtech/geowave#1646]
Standalone GeoWave install supports the following utility commands (geowave help util):

1. accumulo
1. grpc
1. hbase
1. landsat
1. redis
1. sentinel2

Source code built GeoWave supports the following utility commands (java -cp ~/dev/workspace/geowaveOS/deploy/target/geowave-deploy-1.1.0-SNAPSHOT-tools.jar org.locationtech.geowave.core.cli.GeoWaveMain help util):
1. accumulo
1. grpc
1. landsat
1. python
1. sentinel2

I need to be able to build GeoWave with support for `redis`. How do I do this?

My build steps:
1. mvn clean install -Dfindbugs.skip=true -Dformatter.skip=true -DskipITs=true -DskipTests=true
1. mvn package -P geowave-tools-singlejar -Dfindbugs.skip=true -Dformatter.skip=true -DskipITs=true -DskipTests=true

**Comment by jdgarrett** [comment]
This is because those commands are built and installed as installer plugins.  You can package up the installer plugins with the following command: `mvn package -P build-installer-plugin -DskipTests -Dfindbugs.skip -Dspotbugs.skip`.  This will package artifacts in the `extensions/cli/redis-embed/target/installer-plugin` directory.  Include those artifacts on the classpath when running GeoWave to have access to the `geowave util redis` command.

**Comment by pfrollo** [comment]
Thank you for the info. Would it be useful to document this?
