### ISSUE TITLE
Expose Cassandra cluster configuration options

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geowave#1744]
Currently its not possible to configure the Cassandra session in any significant way.
I'm happy to offer up a PR for this issue if we can agree on acceptable approach that's likely to be merged.

## Exposition

`CassandraDataStore` construction accepts [`CassandraOperations` and `CassandraOptions`](https://github.com/locationtech/geowave/blob/cef770e60416751376b11519e9cc875339b4c53c/extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/CassandraDataStore.java#L36-L45) instance.

`CassandraOperations` is the "DAO" and holds the Cassanda [`session`](https://github.com/locationtech/geowave/blob/cef770e60416751376b11519e9cc875339b4c53c/extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraOperations.java#L89) and actually provides the relevant methods.

`CassandraOperations` initilizeds the `session` [during construction](https://github.com/locationtech/geowave/blob/cef770e60416751376b11519e9cc875339b4c53c/extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraOperations.java#L104-L114) and further uses the `private final session` field in all the [method implementations](https://github.com/locationtech/geowave/blob/cef770e60416751376b11519e9cc875339b4c53c/extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraOperations.java#L247-L254). So sub-classing this class is not really a viable option to inject session configuration.

[`SessionPool`](https://github.com/locationtech/geowave/blob/master/extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/util/SessionPool.java) is a singleton and can't really do much about configuring the Cassandra `Cluster`.
We do get the `options` passed into `SessionPool.getSession` but only thing that is done is getting and caching on contact points.

## Alternatives

One option would be try to flesh out the Cassandra options that are passed from command line. This seems challenging because [`Cluster.Builder`](https://docs.datastax.com/en/drivers/java/3.5/com/datastax/driver/core/Cluster.Builder.html) has a decent number of configurations some of which require intermediate construction. At a first glance it may be a whole set of SPIs that would need to be introduced and that's a lot of weight to carry around in the project.

Easier and flexible option would be to turn `CassandraOperations` into an interface which would allow the user to sub-class it. That would place the responsibility of managing the session pool on the client code but that does not seem out of line. I believe swap of `CassandraOperations` to interface or abstract class and addition of `CassandraOperationsImpl` would also preserve binary comparability, making it easy to release. I think abstract class makes the most sense here so user can avoid copy/pasting the implementation.

**Comment by rfecher** [comment]
our deployments rely on doing most reasonable configuration through externalized config rather than exploiting custom programmatic extensions so if at all possible reasonable configuration options would be ideally exposed in `CassandraOptions` and passed to `SessionPool`.  However, I understand that'd start to get pretty heavy and difficult to maintain if we just translated the options in datastax `Cluster.Builder`. Is there an option on the builder here that is fairly generally applicable that we may just want to add through the externally configurable codepath described above?

Regardless, would something as simple as [this](https://github.com/rfecher/geowave/commit/1edb61aad289731e6f6bfeb7d51c6db306822da1) get you what you want?  With a constructor that allows you to supply Session you can build and manage the Cassandra Session however you want and then pass it along to GeoWave with:
`new CassandraDataStore(new CassandraOperations(<options>, <your Session>), <options>)`

**Comment by echeipesh** [comment]
Hey, that's an even simpler option I missed. The `session` is static once constructed, so that totally works.

**Comment by rfecher** [comment]
cool, PR #1747 is in

**Comment by echeipesh** [comment]
thank you
