### ISSUE TITLE
Provide more detailed documentation of fields in key

### ISSUE THREAD

**Issue by keith-turner** [locationtech/geowave#250]
I was looking at the [Accumulo Persistence](https://ngageoint.github.io/geowave/docs/accumulo.html) page and wondering about some of the fields.   I felt I could guess at the purpose of some of the fields, but more detailed documentation for each field would really help one understand the persistence model. A list/table of fields and a short description (w/ links for further documentation) would be nice.  

In addition to outlining the purpose of individual fields, documenting the thought process behind the ordering of the fields would also be nice.   For example is there a reason that `Adapter ID` comes before `Data ID`?

**Comment by jwomeara** [comment]
I'm going to take a stab at answering this, but I'm counting on Rich and Chris to back me up if I get something wrong.  

IndexID is composed of three parts; tier, bin and hilbert value. 

For vector data, GeoWave uses a tiered index strategy with 15 levels, each of increasing precision by default.  The tier component of the IndexID specifies the tier where this row was stored.  

The bin is used to identify where this row lies on the space filling curve (SFC).  If we break the map into "buckets" based on the SFC, the bin is used to determine which "bucket" this row falls into.  The [Theory Overview](https://ngageoint.github.io/geowave/docs/theoryoverview.html) page has a good illustration of this concept under the Hilbert SFC section.  

The Hilbert value is the value derived from the Hilbert SFC transform.  It maps an n-dimensional value to a single dimension.  

AdapterID is used to identify the adapter that was used to write (and subsequently to read) the row.  Each data adapter is actually persisted in the GEOWAVE_METADATA table.  This adapter id can be used to recall the data adapter from that table.  For instance, with the FeatureDataAdapter this value represents the Simple Feature type name.  

DataID is a value which is unique to this particular entry.  For instance, with the FeatureDataAdapter this value represents the data id of the feature.  

AdapterID length and DataID length are used to parse the AdapterID and DataID from the row.  As length of these fields is variable, we need to know how many bytes to read to reconstruct each value.  It should be noted that size in bytes of each of these lengths is static.

# of Duplicates indicates whether this entry has duplicate entries within the table.  If there are no duplicates, the value will be -1.  However, if this is a polygon or line, the feature may span across multiple rows.  This is useful when deduplicating and when deleting entries by data id.  

Is this the kind of information you're looking for?

**Comment by keith-turner** [comment]
The reason I was reading the GeoWave documentation is because I was looking for software that used Accumulo and documented how it used Accumulo for a blog post I am writing for [ACCUMULO-3567][1].  I found the Accumulo Persistence page, which is quite wonderful relatively speaking.   However I could not relate everything on the Accumulo Persistence page to the concepts on your theory page.

Are their examples anywhere going from a point on map to an Accumulo key?  At the end of the [Theory Overview][2] page there is a 16x16 map of the earth.  If I choose a point on that map, what would the Accumulo key look like (that map does not have the SFC lines or bucket numbers, so maybe its a bad example)?   For example I suspect the Tier field would record in some way that the map is 16x16?   For that map would the Bins fields be a number in the range [0,255] depending on which bucket the point was located?  What would be in the Hilbert field?

[1]: https://issues.apache.org/jira/browse/ACCUMULO-3567
[2]: https://ngageoint.github.io/geowave/docs/theoryoverview.html

**Comment by keith-turner** [comment]
> AdapterID length and DataID length are used to parse the AdapterID and DataID from the row. As length of these fields is variable, 

Why do the lenght fields come after?   How do you know where the length fields start if the previous fields are of arbitrary length?

I have some more questions about AdapterID and DataID, but I suspect those could be answered by existing documentation or javadoc.  I will look next week for links that may be useful for this page.

**Comment by chrisbennight** [comment]
Re: Better map of accumulo keys to geo extents.   I put together some more graphics here - let me know if these help  (i didn't actually superimpose the earth graphic in the SFC grid, but it's conceptually there)

https://dl.dropboxusercontent.com/u/6649380/Presentation2/expl1.PNG
https://dl.dropboxusercontent.com/u/6649380/Presentation2/expl2.PNG
https://dl.dropboxusercontent.com/u/6649380/Presentation2/expl3.PNG
https://dl.dropboxusercontent.com/u/6649380/Presentation2/expl4.PNG

Hopefully those help a bit.

Re: key 
We have a metadata / data table mapping for each "geowave namespace".  The metadata table contains the index lookup - and this is what defines the number of tiers and configuration of each (cardinality per dimensions, number of dimensions, normalization, etc.).   
The tier is an index into that - so yeah, gives the 16x16 or whatever map pointer.  
The bins is a bit out - as it's only used for "unbounded" (or periodic indexes).  The Hilbert (or more generally SFC field) is the bucket.

There's a bit more on the ingest side - for points this is about all you need (you actually don't need the tiers for points - just one index level).   For lines and polygons there are some other metrics for "how" you fit them  (you could insert a polygon in the first "bucket" that fully contained it, or we could try and do a better fit and allow 4, 100 buckets (at higher resolution), etc.  - there's pro's and cons, tuning, etc. here).  (This portion I didn't include in the diagrams, but can put together something on this)

Re: length fields - it was to preserve significance in sorting - we didn't want the length sorting to take priority over the adapter, etc. instances

**Comment by chrisbennight** [comment]
@keith-turner 
A couple of other points related to your blog post for https://issues.apache.org/jira/browse/ACCUMULO-3567
These are just random things off the top of my head where I think we make more than the standard use of accumulo, so might be interesting things depending on the scope of your post.
* Tablet locator
  * We made use of this (despite it not being in the public api) for I think some of the same reasons other people on the list have been  (our use is here: https://github.com/ngageoint/geowave/blob/master/geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/mapreduce/input/GeoWaveInputFormat.java ).  Bascially we can generate 10's of thousands of ranges easily with a geospatial query decomposition.  We wanted to roll these up to a more reasonable amount of ranges - and we could do that purely at the range level (strategies like combining ranges to minimize "non range" inclusions) - but it quickly became obvious that we want want to take split points into account here;  if we had  the range prefixes  2, 3, 5, 8   and wanted 3 ranges we might naturally pick (2-3), (5), and (8)   - but what if we had a table split between (2) and (3)?   in that case we might want (2), (3-5), and (8)   (assuming there was no split between 3 and 5).   
  * You can see the use of maven munge in there - we are looking to support the same versions the accumulo team does, so n-1;   we used munge to handle the breaking changes between 1.5 and 1.6 in this api  (and hope to drop it shortly - it doesn't play nicely with some of the code coverage tools)
* Streaming statistics / summary / aggregate capability
  * We actually came upon the same pattern that Bill Slacum briefed at one of the accumulo meetups (ref: http://www.slideshare.net/BillSlacum/aggregating-in-accumulo ).   We had gone a bit farther to handle multiple permutations of visibilities on the aggregates;  basically we have an interface (mergeable) and the code in there has to be commutative and associative.  This code can be processed server or client side.  Typical use case is in memory batching/processing client side, with results sent to the server  (though a value could be sent directly to the server, it would result in 2x mutations per entry).  On the server side one set of iterators run at major and minor compaction.  These take multiple results that can be compined, apply the Mergeable function, and write out a set of values per unique  byte[] visibility value (wanted to stay away from interpreting the visibiliy here to keep it more generic - this does mean if the underlying values aren't sorted we have some inefficiency - but everything still works).   A scan time iterator takes the users authorizations, scans through the values, and applys the Mergeable function to each summary/aggregate they can see.  This should give a real time value that would be equivalent to running a full table scan/calculation with their authorizations.   I think this is a really interesting piece as it makes what I think is solid use of Accumulo iterator design patterns (in keeping with the original intent), and handles the issue of ABAC control on aggregate/summary stats as well.
  * Initial use cases for this are things like calculating bounding boxes for geographic and temporal extents;  on the roadmap are statistics for query planning (cardinality (hyperloglog+), distribution (bloom filter that shows the distribution of values of some attribute at some precision), etc.)
  * This actually feels like it could almost be a core accumulo capability (it's pretty generic) - except there's no build in "index" or "stats" concept in accumulo.  And it's a bit of a stretch for the existing metadata concept (really it's a metadata per table).   But definitely as a standard pattern/practice (maybe for inclusion in accumulo-recipies, etc.) or as a separate project (much less ambitious, but similar to fluo on how it fits together).
* Rendering/z-order occlusion at the iterator level
  * I think this is interesting because you can only really do it if your database gives you the ability to short circuit reads.  Basically when someone wants to render a graphic over a geospatial extent all systems now query from the DB *all* the data in that extent, the draw it.  They might shortcircuit the drawing at the server level (only color pixels once, or X number of times (alpha blending, etc.)) - but they still had to read all the data on disk, and move it over the network.   
  * What we do (currently only for pixels) is define a transform (for a given geographic extent) between pixel space and "index space" (index ranges).   At the index (in an iterator) we start scanning, and when we have a result for a pixel (index range), we simply seek to the start of the next range.   This means our worst case performance is only a function of the number of pixels we draw.  Here's a graphic:  https://dl.dropboxusercontent.com/u/6649380/decimation.png 
  * What probably *will* be a huge abuse of iterators, is we are looking to extend this to line and polygon rendering.  With pixels we assumed that one value translates to one pixel drawn (it doesn't always have to, but that's a limit).   With shapes one value could color one pixel, or the entire tile, or some portion of it.  We effetively have to "Draw" it to find out.   And since styling impacts this we have to actually render it based on the full styling engine.
  * @rfecher has a proof of concept that is up and working, and in an Accumulo iterator translates a query range into an image, and actually returns that rendered image as the value (variation on the transforming iterator + whole row iterator, etc.)   Due to the scope of what's in an iterator it's slightly more complicated, but he is working on this now - this let's us both distribute the rendering load, and short circuit reads.  The short circuiting reads is the big win, as it allows quick interaciton with massive amounts of data.   Here's a graphic for what Rich is working on now:  https://dl.dropboxusercontent.com/u/6649380/distributed2d.png
* Transactions
  * If we move to fluo some of this might be OBE, but right now we are using visibilities (optionally) as methods of creating transactions.  One of the specifications we support - WFS-T  (method for users uploading features over a REST call) requires that the server implement transaction support with the normal semantics.   We have pre-configured an enumerated set of transaction visibilities (upper limit on the number of concurrent transactions), and use those to represent the mutated objects.
* Things we wrestle with
  * Hotspotting / distribution of data.  Probably a pretty common things, but the typical tradoffs of massively striped contiguous regions being the best for querry, but poor for analytics (lots of network IO moving the data together).   
  * Query - our use cases are typically *much* more query focused than ingest focused.  Normal geospatial systems use R-trees or variants for the most port (non-distributed systems), and even when in memory rebalancing, locking, etc. cause ingest to be slow.  Since we map to a grid and don't have to rebalance ingest becomes effectively a non-issue.  For the typical Accumulo use case (mailing list, etc.) it seems sometimes more effort is spent on ingest, or big batch queries.  We are really in the low latency query area / need case, and there's not as much out there on that.
  * Secondary indexes / indexing.  - pretty straightforward, lots of patterns, but I kind of feel like it's re-inventing the wheel constantly.   Lucene on Accumulo would be nice!   

Those are just a few random thoughts.

**Comment by keith-turner** [comment]
> Hopefully those help a bit.

@chrisbennight expl[1-4].PNG are awesome, they helped more than a bit.   They really helped me mentally map the key structure to the concepts!!!

For me the understanding came in a non-linear way as I went back and forth looking at the images.  Some thoughts about the images.  Based on this exercise I went through  of trying to extract meaning from the images,  I think using more consistent terminology throughout the explanations within the images would help others.  

 * **expl1.PNG** :   The text in this particular image overloads the word "index", "index" is used for multiple purposes in this image and therefore loses some ability to convey information.    Could you say "Multiple tiers are stored in a single table.  Each tier indexes multidimensional data at a different resolution." for the lower text?   For the text on the right could you say "Metadata about tiers is stored in another table called METADATA.  This includes number of tiers, number of dimensions, cardinality of each tier, and normalization".  
 * **expl3.PNG** : This was extremely helpful.  I now understand the purpose of this bin field, it was kinda mysterious before.    It would be very helpful to work in the same language used in expl1, specifically use of the words "normalization" and "cardinality".  For example  : "The METADATA table specifies  how to normalize a year to [-0.4,0.4] with a cardinality of 5.  It also specifies each bin represents a year."
 * **expl4.PNG** : really nice.  Could possibly change "is in scope" to "is in same tablet".
 * **decimation.png**, I think a title like the following would be useful  "Efficiently checking for geometry presence in four pixels".   IMO  the image provide an extremely good overview of accomplishing something w/o stating explicitly what its trying to accomplish.  I think most people could work backwards, but it does not hurt to make it explicit.    Also, if one of the 4 quadrants had no data, it would make the example slightly more informative.

**Comment by keith-turner** [comment]
> Rendering/z-order occlusion at the iterator level 

If you have time, I think a blog focused post about using Accumulo to accomplish Rendering, z-order occlusion, and short circuit reads would be really interesting.   This blog post could posted on blogs.apache.org. Or it could be posted somewhere else and tweeted from the Accumulo twitter account and posted on the user list.   With Fluo, we are posting blog post on the fluo web site.   I think I announced these on the accumulo user list, I can not remember.   I did not request to have a link tweeted, but should have.

> Transactions 

Do you want single row or multi-row transactions?  Single row transactions can easily be accomplished using conditional mutations.

> Tablet locator

So I suppose you would really like to see something done for [ACCUMULO-2883][1]?

> Things we wrestle with 

Are there any Accumulo tickets you think need to be opened?

[1]: https://issues.apache.org/jira/browse/ACCUMULO-2883

**Comment by rfecher** [comment]
>Do you want single row or multi-row transactions? Single row transactions can easily be accomplished using conditional mutations.
The "transaction" that we talk about with supporting WFS-T is better characterized with "session."  WFS-T is the add/modify/delete extension to a common standard in the geospatial world, and it supports a concept of "transactions" which would basically be an analysts session where they can do anything they want in their geospatial shoebox prior to committing it to the gold copy.  So its not so much a concern of atomic operations as offering a play area separate from the gold copy.  For this we mark the analysts' add/deletes with their unique transaction identifier within the visibility column and then remove the transaction ID from the visibility when they commit it.
>Are there any Accumulo tickets you think need to be opened?
Personally, I think the one stop shop for secondary indexing, or Lucene on Accumulo is worthy of a separate project so there's not so much duplication of effort for such a common problem.
