### ISSUE TITLE
Wrap commandline operations with REST endpoints

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#785]

**Comment by datasedai** [comment]
Basically, see if there is a way to dynamically expose the operations using the ability to dynamically set parameters using JCommanderPropertiesTransformer, and our SPI interface.  Needs some authorization capability possibly, but basically dynamically generate the REST functions, and maybe have some capability to ingest files via file upload/submit instead of via command line property.

**Comment by mawhitby** [comment]
The first part of this was completed by some of the Cornell students we worked with during the second semester of the 2016 school year. Their work was added in #1097.
