### ISSUE TITLE
geowave vs Hadoop jar

### ISSUE THREAD

**Issue by mawhitby** [locationtech/geowave#832]
Currently we have to run kde and other jobs using Hadoop jar /geowave-tools.jar [options]. We would like to be able to run them simply using the geowave command which is effectively using java -jar  /geowave-tools.jar [options]. to run the job.

**Comment by datasedai** [comment]
Related to #236 & #817. 

The "hadoop jar" and "yarn jar" syntax is used when you have items in your hadoop_classpath that must be included when your jar is sent to individual hdfs nodes.  If you have nothing in that classpath, then you don't need to use that syntax, you can just use "java -jar ...tools.jar" or "geowave analytic ..." etc.

Something that complicates this issue is that our formats are separated into their own jars. When including the jar in the hadoop_classpath, it seems as though the format jars get a class not found exception for any classes referenced in the tools jar.  The solution to this was to include the tools jar in hadoop_classpath as well as included it on the command line with "hadoop jar".

**Comment by rfecher** [comment]
in the past to add the plugins directory to the hadoop classpath when running "hadoop jar" or "yarn jar" I've added this to the mapred-site.xml file on the client that I submit the job from:

YARN configuration:

mapred-site.xml

<property> 
    <name>mapreduce.application.classpath</name> 
    <value>$HADOOP_MAPRED_HOME/*,$HADOOP_MAPRED_HOME/lib/*,$MR2_CLASSPATH,/usr/local/geowave/tools/plugins/*</value> 
</property>
